### ISSUE TITLE
Does not compile under Java 8

### ISSUE THREAD

**Issue by sebastian-stephan** [liquid-mind/deflector#3]
```
error: TypeVariableImpl is not abstract and does not override abstract method 
getAnnotatedBounds() in TypeVariable
```

[TypeVariableImpl](https://github.com/liquid-mind/deflector/blob/master/src/ch/liquidmind/deflector/reflection/TypeVariableImpl.java) does not implement getAnnotatedBounds() from TypeVariable

Java 8 introduced an abstract method getAnnotatedBounds() in [TypeVariable](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/TypeVariable.html)

**Comment by johnbrush** [comment]
Added missing methods; fixed.
